### PR TITLE
Builds working for Windows, Linux and MacOS / OSX

### PR DESCRIPTION
**Pull request by ghost**
Hi Javier,

It seems that everything works now. I had to disable the static version of the library for Linux, because it had many problems (as is often the case with static libraries on Linux 😄 )

Cheers,

Dimitri

### CODE REVIEW

**Comment by jgsogo** [comment]
wow! It looks great!

**Comment by ghost** [comment]
I'm glad you like it :+1:  
Many thanks for accepting the modifications. We can get rid of my fork now. :smile:

**Comment by jgsogo** [comment]
Wait a little bit. I need to merge those changes from `master` to de "released" branches.

**Comment by ghost** [comment]
Sure! (In any case I meant I'll do it over the weekend, not like now now :smile: )

**Comment by jgsogo** [comment]
Everything seems to work like a charm, jobs on all branches have passed! \o/

**Comment by ghost** [comment]
Wonderful! Thanks Javier! I'll throw away the fork and re-link small3d to your package.

**Pull request merged**
